/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    PriceList: typeof import('./src/components/PriceList.vue')['default']
    ProductList: typeof import('./src/components/ProductList.vue')['default']
    ProductsList: typeof import('./src/components/ProductList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StoreNav: typeof import('./src/components/StoreNav.vue')['default']
  }
}
